### ISSUE TITLE
cool work! Add  AI/LLM-gerenated text detection model

### ISSUE THREAD

**Issue by WangRongsheng** [FreedomIntelligence/ChatGPT-Detection-PR-HPPT#3]
So cool work!

we are also working on something related to AI/LLM-gerenated text detection, can you evaluation our model on this dataset?

1. English detection model: https://modelscope.cn/models/QiYuan-tech/LLM-Detector-Small-en/summary
2. Chinese detection model: https://modelscope.cn/models/QiYuan-tech/LLM-Detector-Small-zh/summary

**Comment by Reasercher-wrs** [comment]
|Model|Test Set|ACC|
|:-|:-|:-|
|[LLM-Detector-Small-en](https://modelscope.cn/models/QiYuan-tech/LLM-Detector-Small-en/summary)|[HPPT/test.json](https://github.com/FreedomIntelligence/ChatGPT-Detection-PR-HPPT/blob/main/Dataset/HPPT/test.json)|60.98%|
|[LLM-Detector-Small-en](https://modelscope.cn/models/QiYuan-tech/LLM-Detector-Small-en/summary)|[HC3/test.json](https://github.com/FreedomIntelligence/ChatGPT-Detection-PR-HPPT/blob/main/Dataset/HC3/test.json)|83.46%|
|[LLM-Detector-Small-en](https://modelscope.cn/models/QiYuan-tech/LLM-Detector-Small-en/summary)|[llama_data/test.json](https://github.com/FreedomIntelligence/ChatGPT-Detection-PR-HPPT/blob/main/Dataset/llama_data/test.json)|58.54%|
|[LLM-Detector-Small-zh](https://modelscope.cn/models/QiYuan-tech/LLM-Detector-Small-zh/summary)|[Chinese_data/polished_abstract/test.json](https://github.com/FreedomIntelligence/ChatGPT-Detection-PR-HPPT/blob/main/Dataset/Chinese_data/polished_abstract/test.json)|67.48%|

**All data is out-of-domain for LLM-Detector!** Is [HPPT/train.json](https://github.com/FreedomIntelligence/ChatGPT-Detection-PR-HPPT/blob/main/Dataset/HPPT/train.json) used to train the model?
